version: "2"

run:
  timeout: 5m

linters:
  disable:
    - contextcheck
    - exhaustruct
    - errcheck
  enable:
    - govet
    - bodyclose
    - dupl
    - gocritic
    - gocyclo
