repos:
  # ================
  # General
  # ================
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=700']  # Increase the limit to 700 KB
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: detect-private-key
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
        name: Check JSON syntax
        exclude: sdk/typescript/tsconfig.json

  # ================
  # Go
  # ================
  - repo: https://github.com/golangci/golangci-lint
    rev: v2.12.2
    hooks:
    - id: golangci-lint


  # ================
  # Python
  # ================

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.0
    hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix, --config=pyproject.toml, --show-fixes ]
    # Run the formatter.
    - id: ruff-format
      args: [--config=pyproject.toml, --verbose ]

  - repo: https://github.com/astral-sh/ty-pre-commit
    # ty version.
    rev: v0.0.64
    hooks:
    - id: ty
