FROM ubuntu:24.04 as base

# setup uv
COPY --from=ghcr.io/astral-sh/uv:0.9.17 /uv /uvx /bin/

RUN uv python install

WORKDIR /tests

COPY pyproject.toml uv.lock ./

COPY tests/ .

RUN uv sync --package tests