[scheduler]
workers = 4
buffer-size = 128

[server]
port = 9876

[log]
level = "INFO"
format = "json"
disable-timestamp = true

[engine]
half-life = "168h"
cache-capacity = 1024

[db]
precision = "float32"
default-top = 10
default-depth = 2
seed-size = 64

[db.hashing-function]
name = "xxhash"
