name: Open an Issue
description: |
  Feel free to report bugs, suggest features, or submit proposals here
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing to BuildKit through issue submission!
        - If you're new to this repository, we encourage you to review our [issue reporting guide](https://github.com/moby/buildkit/blob/master/.github/issue_reporting_guide.md) which outlines the key information you should provide for the process to go smoothly.
        - For general questions about using BuildKit, consider joining the `#buildkit` channel on the Docker Community Slack, where a broader community can provide support and insights.

  - type: textarea
    validations:
      required: true
    attributes:
      label: Description
      description: Share your bug report, feature request or proposal here
      placeholder: Type your description here...
