name: Pre-commits
on:
  push:
    branches: [main]
    paths:
      - "sdk/python/**"
      - ".github/workflows/python.yaml"
  pull_request:
    paths:
      - "sdk/python/**"
      - ".github/workflows/python.yaml"

jobs:
  pre-commits:
    runs-on: ubuntu-22.04
    env:
      AWS_PROFILE: AWS_PROFILE
    steps:

      - name: Check out code
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version-file: "pyproject.toml"

      - name: Install pre-commit dependencies.
        run: |
          uv tool install pre-commit

      - name: Run pre-commit on all files.
        id: pre-commit-all
        run: |
          pre-commit run --verbose --all --all-files
