name: TypeScript SDK

on:
  push:
    branches: [main]
    paths:
      - "sdk/typescript/**"
      - ".github/workflows/typescript.yaml"
  pull_request:
    paths:
      - "sdk/typescript/**"
      - ".github/workflows/typescript.yaml"

permissions:
  contents: read

jobs:

  lint:
    name: Lint Typescript SDK
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20, 22]
    steps:
      - uses: actions/checkout@v5

      - name: Lint typescript sdk ${{ matrix.node }}
        run: make lint-ts

  test:
    name: Test Typescript SDK
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sdk/typescript
    strategy:
      matrix:
        node: [20, 22]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: sdk/typescript/package-lock.json

      - name: Build
        run: make build-ts

      - name: Test
        run: make test-ts
